export const possibleTabs = [
  { id: '/app/dashboard', name: 'Tableau de bord' },
  { id: '/app/enterprises', name: 'Entreprises' },
  { id: '/app/external-links', name: 'Liens externes' },
  { id: '/app/faq', name: 'FAQ' },
  { id: '/app/products', name: 'Produits' },
  { id: '/app/tools/credit', name: 'Avoir' },
  { id: '/app/tools/ddns', name: 'DDNS' },
  { id: '/app/tools/emails/send', name: 'Nouvelle email' },
  { id: '/app/tools/emails', name: 'Mails' },
  { id: '/app/tools/external-links', name: 'Liens externes' },
  { id: '/app/tools/global-turnover', name: 'CA global' },
  { id: '/app/tools/news', name: 'Actualités' },
  { id: '/app/tools/predefined-messages', name: 'Messages prédéfinis' },
  { id: '/app/tools/predefined-texts', name: 'Textes prédéfinis' },
  { id: '/app/tools/representatives-map', name: 'Représentants' },
  { id: '/app/tools/representatives-turnover', name: 'CA des représentants' },
  { id: '/app/tools/scheduler', name: 'Agenda' },
  { id: '/app/tools/vva', name: 'VVA' },
];
