version: '3.8'

services:
  vizion-test:
    image: vizion-test
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      type: bind
      source: ./
      target: /srv/app
    ports:
      - 3001:3001
