enum AssistanceState {
  PRISE_EN_CHARGE = 'PRISE_EN_CHARGE',
  RECEPTION = 'RECEPTION',
  ANALYSE_REPARATION_EXPEDITION = 'ANALYSE_REPARATION_EXPEDITION',
  ARCHIVE = 'ARCHIVE',
}

export default AssistanceState;
