enum FaqAccessLevel {
  PUBLIC = 'PUBLIC',
  INTERNE = 'INTERNE',
  PROFESSIONNEL = 'PROFESSIONNEL',
  INTERNE_IA = 'INTERNE_IA',
  PUBLIC_IA = 'PUBLIC_IA',
  ATTENTE = 'ATTENTE',
  VIZIA_COMPORTEMENT = 'VIZIA_COMPORTEMENT',
}

export default FaqAccessLevel;
