enum FileType {
  AFFAIRE = 'AFFAIRE',
  CONTACT = 'CONTACT',
  PRODUIT = 'PRODUIT',
  TACHE = 'TACHE',
  CLIENT = 'CLIENT',
  FOURNISSEUR = 'FOURNISSEUR',
  GESTION_PROJET = 'GESTION_PROJET',
  ASSISTANCE = 'ASSISTANCE',
  REPORT = 'REPORT',
  SAV_FOURNISSEUR_TRANSPORT = 'SAV_FOURNISSEUR_TRANSPORT',
  FAQ = 'FAQ',
  COMMANDE = 'COMMANDE',
  SAV = 'SAV',
  PROFORMA = 'PROFORMA',
  INVOICE = 'INVOICE',
  NOTICE = 'NOTICE',
  FABRICATION = 'FABRICATION',
  FORMATION = 'FORMATION',
  CONTROL_FACT = 'CONTROL_FACT',
  DEFAULT = 'DEFAULT',
}

export default FileType;
